name: Deploy

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        node-version: 12.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Deploy Dev
      run: |
        python snowchange/cli.py -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -u ${{ secrets.SNOWFLAKE_USER }} -r ${{ secrets.SNOWFLAKE_ROLE_DEV }} -w ${{ secrets.SNOWFLAKE_WH }} -d ${{ secrets.SNOWFLAKE_DB_DEV }} -c ${{ secrets.SNOWFLAKE_DB_DEV }}.metadata.change_history --create-change-history-table
      if: github.ref == 'refs/heads/dev'
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    - name: Deploy Prod
      run: |
        python snowchange/cli.py -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -u ${{ secrets.SNOWFLAKE_USER }} -r ${{ secrets.SNOWFLAKE_ROLE_PROD }} -w ${{ secrets.SNOWFLAKE_WH }} -d ${{ secrets.SNOWFLAKE_DB_PROD }} -c ${{ secrets.SNOWFLAKE_DB_PROD }}.metadata.change_history --create-change-history-table
      if: github.ref == 'refs/heads/main'
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}